// Theme definitions - 3 themes for day-time use

export const THEMES = {
  mono: {
    id: 'mono',
    name: 'Mono',
    bg: '#FFFFFF',
    panel: '#FFFFFF',
    panel2: '#F7F7F7',
    panel3: '#FAFAFA',
    border: '#EAEAEA',
    borderSoft: '#F0F0F0',
    text: '#1A1A1A',
    textDim: '#8B8B8B',
    textMute: '#C0C0C0',
    accent: '#1A1A1A',
    success: '#4A7C59',
    warn: '#C97B6B',
    q1: '#1A1A1A',
    q2: '#4A4A4A',
    q3: '#7A7A7A',
    q4: '#A8A8A8',
  },
  beige: {
    id: 'beige',
    name: 'Beige',
    bg: '#FAF8F5',
    panel: '#FFFFFF',
    panel2: '#F5F1EB',
    panel3: '#FBF8F3',
    border: '#EAE3D9',
    borderSoft: '#F0EBE2',
    text: '#3A3128',
    textDim: '#9A8F7F',
    textMute: '#C5B8A5',
    accent: '#8B6F47',
    success: '#5A7A4F',
    warn: '#B8745A',
    q1: '#8B6F47',
    q2: '#A68858',
    q3: '#9B8A73',
    q4: '#B8AA95',
  },
  blue: {
    id: 'blue',
    name: 'Blue',
    bg: '#FAFBFC',
    panel: '#FFFFFF',
    panel2: '#F0F4F8',
    panel3: '#F7FAFC',
    border: '#E3EAF0',
    borderSoft: '#EEF2F6',
    text: '#1F2D3D',
    textDim: '#8A9AAB',
    textMute: '#B8C4D0',
    accent: '#5B7FA3',
    success: '#4A8B6F',
    warn: '#C97B6B',
    q1: '#5B7FA3',
    q2: '#7A9BBE',
    q3: '#96B1C9',
    q4: '#A8B8C8',
  },
};

export const WORKSPACES = {
  work: { id: 'work', label: '업무', emoji: '💼' },
  self: { id: 'self', label: '자기개발', emoji: '🌱' },
};
