// Theme definitions — 4 seasons (四季節)

export const THEMES = {
  spring: {
    id: 'spring',
    name: 'Spring',
    bg: '#FFFBFC',
    panel: '#FFFFFF',
    panel2: '#FDF2F5',
    panel3: '#FEF8FA',
    border: '#F5DCE3',
    borderSoft: '#FBE9ED',
    text: '#4A2A35',
    textDim: '#A07B86',
    textMute: '#D5B5BE',
    accent: '#D4627A',
    success: '#6E9A6E',
    warn: '#C97B6B',
    q1: '#D4627A',
    q2: '#E89BAD',
    q3: '#F2C6CF',
    q4: '#F8E0E5',
  },
  summer: {
    id: 'summer',
    name: 'Summer',
    bg: '#F8FCFB',
    panel: '#FFFFFF',
    panel2: '#E9F5F1',
    panel3: '#F1F9F7',
    border: '#CCE5DE',
    borderSoft: '#DEECE8',
    text: '#1E3D36',
    textDim: '#6A8F86',
    textMute: '#A8C3BC',
    accent: '#2D8B7A',
    success: '#2D8B7A',
    warn: '#C97B6B',
    q1: '#2D8B7A',
    q2: '#5FAF9E',
    q3: '#8FCABE',
    q4: '#BFDFD8',
  },
  autumn: {
    id: 'autumn',
    name: 'Autumn',
    bg: '#FDF9F4',
    panel: '#FFFFFF',
    panel2: '#F6EADC',
    panel3: '#FBF4E9',
    border: '#E8D5BC',
    borderSoft: '#F1E4D0',
    text: '#3E2916',
    textDim: '#9A7A56',
    textMute: '#C9B394',
    accent: '#B4501C',
    success: '#5A7A4F',
    warn: '#B4501C',
    q1: '#B4501C',
    q2: '#D4793F',
    q3: '#E5A576',
    q4: '#F0CBAB',
  },
  winter: {
    id: 'winter',
    name: 'Winter',
    bg: '#F8FAFC',
    panel: '#FFFFFF',
    panel2: '#E8EFF5',
    panel3: '#F0F5FA',
    border: '#CDD9E4',
    borderSoft: '#DDE6EE',
    text: '#1A2B3E',
    textDim: '#6E839A',
    textMute: '#A8B8C8',
    accent: '#2C4A6E',
    success: '#4A7C6F',
    warn: '#B8745A',
    q1: '#2C4A6E',
    q2: '#547593',
    q3: '#8AA3BA',
    q4: '#BDCCD9',
  },
};

export const WORKSPACES = {
  work: { id: 'work', label: '업무', emoji: '💼', defaultTheme: 'winter' },
  self: { id: 'self', label: '자기개발', emoji: '🌱', defaultTheme: 'spring' },
};
